services: 
  backend:
    container_name: backend
    build:
      context: ./Backend
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=storefront
      - POSTGRES_DB_TEST=store_front_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "3000:3000"
    networks:
      - storefront
    depends_on:
      - postgres